spring:
  # Database Configuration for Testing (H2 in-memory)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 2
      minimum-idle: 1

  # JPA Configuration for Testing
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # H2 Console for testing (if needed)
  h2:
    console:
      enabled: true
      path: /h2-console

# Management endpoints for testing
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Logging for testing
logging:
  level:
    com.programmingmukesh.auth: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.test: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Test specific properties
app:
  environment: test