services:
  # Service Registry (Eureka)
  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    container_name: crm-service-registry
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - EUREKA_URL=http://service-registry:8761/eureka/
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: crm-api-gateway
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_URL=http://service-registry:8761/eureka/
      - APP_ENVIRONMENT=docker
      - LOG_LEVEL_APP=DEBUG
    networks:
      - crm-network
    depends_on:
      service-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 45s

networks:
  crm-network:
    driver: bridge