spring:
  application:
    name: users-service
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/users_service_db
    username: users_user
    password: users_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        # Fix for LazyInitializationException
        enable_lazy_load_no_trans: false
        # Ensure proper session management
        session:
          events:
            log: false
    open-in-view: false
  
  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    schemas: public
    table: flyway_schema_history

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-null-map-values: false
      write-empty-json-arrays: false
      write-single-elem-arrays-unwrapped: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    time-zone: UTC
    # Explicitly disable type information in JSON
    default-typing: none

# Server Configuration
server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: false

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,caches,circuitbreakers
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
    caches:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
    redis:
      enabled: true

# Logging Configuration
logging:
  level:
    com.programmingmukesh.users: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/users-service.log

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /api-docs/swagger-config
    urls:
      - url: /api-docs
        name: Users Service API
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    display-request-duration: true
    doc-expansion: none
    deep-linking: true
  packages-to-scan: com.programmingmukesh.users.service.users_service.controller
  paths-to-match: /api/**

# Custom Application Properties
app:
  user:
    default-timezone: UTC
    default-language: en
    default-theme: light
    profile-image-max-size: 5242880 # 5MB
    
  validation:
    password-min-length: 8
    username-min-length: 3
    
  privacy:
    gdpr-enabled: true
    data-retention-days: 2555 # 7 years
    
  notifications:
    email-enabled: true
    sms-enabled: false
    push-enabled: true

  # Cache Configuration
  cache:
    default-ttl: 3600  # 1 hour
    user-ttl: 1800     # 30 minutes
    search-ttl: 300    # 5 minutes
    stats-ttl: 900     # 15 minutes

  # Error Handling Configuration
  error:
    include-trace: false
    include-cause: false
    max-stack-trace-length: 1000

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      database:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
        permitted-number-of-calls-in-half-open-state: 3
      cache:
        register-health-indicator: true
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 60
        wait-duration-in-open-state: 10s

  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - org.springframework.dao.DataAccessResourceFailureException
          - org.springframework.dao.TransientDataAccessException
          - java.sql.SQLException

  timelimiter:
    instances:
      default:
        timeout-duration: 5s