apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: crm-microservices
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
